<a href="https://colab.research.google.com/github/Akashmadasu1/My_Python_Notes/blob/main/Numpy_Note_Book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Introduction (27-05-2025)

In [ ]:
#what is numpy?
#Numpy is core library for scetififc computing in puthon
#what is the central object in numpy?
#Numpy - Array's
#What is Numpy?
#Arrays are High performance, multidimensional objects which is designed specially for mathmetical operations.
#Array's are ordered, immutable and allows duplicate data

In [ ]:
#what are all different use case of numpy?
"""
1.Dot Product / Inner product
2.Matrix multipication
3.element wise matrix multiplication
4.solving the linear systems
5.inverse
6.determinent
7.choose the random numbers
8.statistics
9.Broadcasting method
"""

**Installation of Numpy**

what is pip?

python package manager

package->modules->libraries->inbuilt codes

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#check the version of numpy?
np.__version__

'2.0.2'

In [ ]:
#how many types of data structures do we have in numpy?
#There 3 types
#1D -- Array's-->Array's with zero columns and specific rows(axis 0)
#2D -- Array's-->Array's with both rows(axis 0) and columns(axis 1)
#3D --> also known as Multidimensional arrays

# Central Object in Numpy is Array

In [ ]:
#How can we create an array?
#Array's can be created from existing data
#1D- Array
l = [1,2,3,4,5]
a = np.array(l)
print(a)

[1 2 3 4 5]


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#I want to see the shape of the array
a.shape
#find the dtype of elements in the numpy array
a.dtype
#find the dimensionality of an array
a.ndim
#find the total number of element present in the array
a.size
#find the memory size in bytes occupied by each element in array
a.itemsize


**Essential method to create an array**

In [ ]:
#create an array from tuple of numbers
t = (1,2,3,4,5)
b = np.array(t)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#create an array from dicitonary?
d1 = {
    'name':'akash'
}
c = np.array(d1)
print(c)

{'name': 'akash'}


In [ ]:
#create an array from the set?
s = {1,2,3,4,5,6}
d = np.array(s)
print(d)

{1, 2, 3, 4, 5, 6}


**essentional method to acess an array**

In [ ]:
a = np.array([1,2,3,4,5])
#print the 1st value
print(a[0])
#print 2,3 from above array
print(a[1:3])
#reverse the above array
print(a[::-1])

1
[2 3]
[5 4 3 2 1]


In [ ]:
#Array's are immutable we can replace the data but we cannot add new elements and we cannont remove elements from arrays
a[2] = 5
print(a)

[1 2 5 4 5]


In [ ]:
#How can we add the new items to the arrays?-->we can add by creating a new variable

**Element wise maths operation**

In [ ]:
b = np.array([6,7,8,9,10])
print(a+b)
#what is vector addition?
#when we apply addition on array of same length and dimensions --> is known as vector addition
#Note:-

[ 7  9 13 13 15]


In [ ]:
c = np.array([9])
print(b+c)
#what is broadcasting method?
#Adding a single element of an array with mutiply elements in another array of same dimension is known as Broad casting method

[15 16 17 18 19]


**Difference between Array vs List**

In [ ]:
l = [1,2,3]
a = np.array(1)
print(dir(a))

In [ ]:
#how can we adding the elements in the list
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
#add the element in an array
b = np.array([5,6,7,8])
c = np.append(a,b)
print(c)

[1 5 6 7 8]


In [ ]:
"MISD---->Multiple input and single destination"

In [ ]:
#find the sqrt of below array's?
a = np.array([10,20,30,40,50,60,70])
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027]


**Dot Prduct**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot=0
for i in range(len(a)):
  dot = dot + a[i]*b[i]
print(dot)

11


In [ ]:
#dot product is vector multiplication of elements and sum of the result
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#Manual method
c = a*b
d = np.sum(c)
print(d)

In [ ]:
#another method
e = np.dot(a,b)
print(e)

In [ ]:
#latest method
f = a@b
print(f)

11


**Speed test b/w Array vs List**

In [ ]:
#import a time calculator to see difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = list(a)
d = list(b)
T=1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)

#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end-start

#create a timer for numpy array
start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end-start

print('time with list',t1)
print('time with list',t2)
print(t1/t2)

time with list 0.328946406999421
time with list 0.002482713999597763
132.49468406458226
