<a href="https://colab.research.google.com/github/Akashmadasu1/My_Python_Notes/blob/main/Numpy_Note_Book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Introduction (27-05-2025)

In [ ]:
#what is numpy?
#Numpy is core library for scetififc computing in puthon
#what is the central object in numpy?
#Numpy - Array's
#What is Numpy?
#Arrays are High performance, multidimensional objects which is designed specially for mathmetical operations.
#Array's are ordered, immutable and allows duplicate data

In [ ]:
#what are all different use case of numpy?
"""
1.Dot Product / Inner product
2.Matrix multipication
3.element wise matrix multiplication
4.solving the linear systems
5.inverse
6.determinent
7.choose the random numbers
8.statistics
9.Broadcasting method
"""

**Installation of Numpy**

what is pip?

python package manager

package->modules->libraries->inbuilt codes

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
#check the version of numpy?
np.__version__

'2.0.2'

In [ ]:
#how many types of data structures do we have in numpy?
#There 3 types
#1D -- Array's-->Array's with zero columns and specific rows(axis 0)
#2D -- Array's-->Array's with both rows(axis 0) and columns(axis 1)
#3D --> also known as Multidimensional arrays

**Central Object in Numpy is Array**

In [ ]:
#How can we create an array?
#Array's can be created from existing data
#1D- Array
l = [1,2,3,4,5]
a = np.array(l)
print(a)

[1 2 3 4 5]


In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(a.size)

5


In [ ]:
#I want to see the shape of the array
a.shape
#find the dtype of elements in the numpy array
a.dtype
#find the dimensionality of an array.
a.ndim
#find the total number of elements present in the array
a.size
#len(a)
#find the memory size in bytes occupied by each element in array
a.itemsize

**Essential method to create an array**

In [ ]:
#create an array from tuple of numbers
t = (1,2,3,4,5)
b = np.array(t)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#create an array from dicitonary?
d1 = {
    'name':'akash'
}
c = np.array(d1)
print(c)

{'name': 'akash'}


In [ ]:
#create an array from the set?
s = {1,2,3,4,5,6}
d = np.array(s)
print(d)

{1, 2, 3, 4, 5, 6}


**essentional method to acess an array**

In [ ]:
a = np.array([1,2,3,4,5])
#print the 1st value
print(a[0])
#print 2,3 from above array
print(a[1:3])
#reverse the above array
print(a[::-1])

1
[2 3]
[5 4 3 2 1]


In [ ]:
#Array's are immutable we can replace the data but we cannot add new elements and we cannont remove elements from arrays
a[2] = 5
print(a)

[1 2 5 4 5]


In [ ]:
#How can we add the new items to the arrays?-->we can add by creating a new variable

**Element wise maths operation**

In [ ]:
b = np.array([6,7,8,9,10])
print(a+b)
#what is vector addition?
#when we apply addition on array of same length and dimensions --> is known as vector addition
#Note:-

[ 7  9 11 13 15]


In [ ]:
c = np.array([9])
print(b+c)
#what is broadcasting method?
#Adding a single element of an array with mutiply elements in another array of same dimension is known as Broad casting method

[15 16 17 18 19]


**Difference between Array vs List**

In [ ]:
l = [1,2,3]
a = np.array(1)
print(dir(a))

In [ ]:
#how can we adding the elements in the list
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
#add the element in an array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.append(a,b)
print(c)

[1 2 3 4 5 6 7 8]


In [ ]:
"MISD---->Multiple input and single destination"

In [ ]:
#find the sqrt of below array's?
a = np.array([10,20,30,40,50,60,70])
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027]


**Dot Prduct**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot=0
for i in range(len(a)):
  dot = dot + a[i]*b[i]
print(dot)

11


In [ ]:
#dot product is vector multiplication of elements and sum of the result
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#Manual method
c = a*b
d = np.sum(c)
print(d)

11


In [ ]:
#another method
e = np.dot(a,b)
print(e)

In [ ]:
#latest method
f = a@b
print(f)

11


**Speed test b/w Array vs List**

In [ ]:
#import a time calculator to see difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = list(a)
d = list(b)
T=1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)

#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end-start

#create a timer for numpy array
start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end-start

print('time with list',t1)
print('time with array',t2)
print(t1/t2)

time with list 0.1529678030001378
time with array 0.0024385510000684008
62.7289742949182


# (28-05-2025)

**Multidimensional Array's**

In [ ]:
import numpy as np

In [ ]:
#create a 2D array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [ ]:
#How can we access the elements from the 2D arrays?
#[row_index,column_index]
#print 1,2,3,4 from above array
print(a[0])
#how can we access the values from particular column and particular row
print(a[1,1])
print(a[0,2])

In [ ]:
#How can we i print the entire 1st column value from below array
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#print(b)
#print(b[2,:])
#print all the values from second row.
print(b[1])
#print(b[2])

[5 6 7 8]


In [ ]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(b)
print(b.shape)
print(b[0,2,1])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)
10


**Transpose**

In [ ]:
#transpose converts rows into columns and columns into rows
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Matrix multiplication**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#apply the dot product
c = np.dot(a,b)
print(c)
print(a@b)

[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


In [ ]:
#find the inverse of an array a?
d = np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#how can i find the diagonal of array a?
a = np.array([[1,2],[3,4]])
e = np.diag(a)
print(e)

[1 4]


In [ ]:
#diagonal on vector returns the matrix
f = np.diag([1,4,5])
print(f)

[[1 0 0]
 [0 4 0]
 [0 0 5]]


In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#print the values from the column 2 and 3
print(b[:,1:3])
print(b[0:3,1:3])
print(b[:,-1:]) #print last column all the values in 2D form

[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4]
 [ 8]
 [12]]


**Boolean indexing**

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
#print(a)
#print the numbers which is more than 2
print(a[a>2])

[3 4 5 6]


In [ ]:
l = [1,2,3,4,5]
print(l>2)

print(l*2)
print(a*2)

In [ ]:
#How can we apply a condition in array
#np.where(condition,True,False)
c = np.where(a>2,a,-1)
print(c)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
#compute the indexes where the condition is true?
#np.argwhere()
i = np.argwhere(a>2)
print(i)

[[1 0]
 [1 1]
 [2 0]
 [2 1]]


In [ ]:
#[10,19,20,30,41,50,61] from above compute the index of even numbers
a = np.array([10,19,20,30,41,50,61])
even = np.argwhere(a%2==0).flatten() #flatten prints the o/p in single line
print(even)

[0 2 3 5]


In [ ]:
a_even = a[even]
print(a_even)

[10 20 30 50]


**reshaping of an array**

In [ ]:
#create a range of array upto 9
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#print a range of numbers from 1 to 10 and reshape into 5 rows and 2 columns
c = np.arange(1,11).reshape(5,2)
print(c)
#print a range of numbers from 1 to 6 and reshape into 2 rows and 3 columns
d = np.arange(1,7).reshape(2,3)
print(d)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[1 2 3]
 [4 5 6]]


**np.newaxis**

In [ ]:
#np.newaxis:- is used to create a axis in the data
a = np.arange(1,7)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
#np.newaxis
d = a[np.newaxis,:]
print(d)
print(d.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
e = a[:,np.newaxis]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [ ]:
#np.array([])
#np.array([[]])
#np.shape
#np.dim
#np.size
#np.dtype
#np.itemsize
#np.dot(arr1,arr2)
#np.sqrt()
#np.min()
#np.linalg.inv(array1)
  #np.where(condition,true,false)
  #np.argwhere(condition) (.flatten())
  #np.arange(start,end)
  #np.reshape(no.row,no.col)
#np.diag(array1 or [vector])
#np.newaxis
#Transpose(T)


# (29-05-2025)


**Concatenation**

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#combine or concatenate the above 2 arrays
#b.shape
c = np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


In [ ]:
c = np.concatenate((a,b),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
d = np.concatenate((a,b.T),axis=1)
print(d)
#Note:- when we concatenate two array's along with the rows we need to check both array have same number of columns
#2.when we concatenate two array's along with the columns we need to check both array have same number of rows

[[1 2 5]
 [3 4 6]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=1)
print(c)
#print the 1st row value
print(c[0,:])
print(c[0])

[[1 2 5 6]
 [3 4 7 8]]
[1 2 5 6]
[1 2 5 6]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=0)
print(c)
#print the 1st row value
print(c[0,:])
print(c[0])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2]
[1 2]


**HSTACK**-->Stack arrays in sequence horizentally

In [ ]:
d = np.hstack((a,b))
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


**VSTACK**-->stack arrays in sequence vertically

In [ ]:
#apply vstack on 1D array
v = np.vstack((arr1,arr2))
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
v = np.vstack((a,b))
print(v)

In [ ]:
print(a)
print(b)

**copying of an array**

In [ ]:
a = np.array([1,2,3])
b = a
b[0]=42
print(a)
print(b)
#np.copy():- if you make any changes in the new array it won't impact on the old array

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0]=42
print(a)
print(b)

**Data Types**

In [ ]:
#convert an array of int64 to int32
a = np.array([1,2,3,4],dtype='int32') #or dtype = np.int32
print(a)
print(a.dtype)

In [ ]:
b = np.array([1.5,2.5,3.5],dtype=np.float32)
print(b.dtype)

**Generating Array's**

In [ ]:
#generate an array's of zero with 2 rows and 3 columns
a = np.zeros((2,3))
print(a)

In [ ]:
b = np.zeros(3)
print(b)

In [ ]:
#generate an array's of ones with 2 rows and 3cols
c = np.ones((2,3))
print(c)

In [ ]:
#generate an array of specific number with particular rows and columns
d = np.full((3,3),5)
print(d)
#np.full((rows,col),number)

In [ ]:
#generate an identity matrix
e = np.eye(3)
print(e)
f = np.identity(3)
print(f)

In [ ]:
#generate a range of numbers upto 9
i = np.arange(10)
print(i)

In [ ]:
#linspace:- splits the data into n equal parts
j = np.linspace(0,10,5)
print(j)
#np.linspace(start,end,no of partitions)

[ 0.   2.5  5.   7.5 10. ]


**Random Numbers**

In [ ]:
#generate random numbers those are uniformly distributed from 0-1
a = np.random.random((3,2))
print(a)

[[0.11703184 0.3047789 ]
 [0.64281055 0.44674468]
 [0.91584923 0.21346254]]


In [ ]:
#generate an array which is normally distributes or gussian distribution
b = np.random.randn(3,2)
print(b)
print(b.mean(),b.std(),b.var())

[[ 0.13362844 -1.15262288]
 [-0.08221819  0.1805594 ]
 [-0.64039427  0.624096  ]]
-0.15615858278014186 0.5829587171485358 0.3398408658994665


In [ ]:
#generate an array of random numbers with 1000 and find the mean varience and std
c = np.random.randn(1000)
print(np.mean(c))
print(np.var(c))
print(np.std(c))

-0.008297239010842923
1.0598617774212824
1.029495885091962


In [ ]:
#generate an array of integers from 3,20 with 2 rows and 3 cols
d = np.random.randint(3,20,size=(2,3))
print(d)

[[15 13 17]
 [10 15  3]]


In [ ]:
#generate an array of numbers upto 6 randomly with size of 10

e = np.random.choice(6,size=10)
print(e)

[3 5 3 0 2 4 3 0 3 2]


In [ ]:
e = np.random.choice([3,5,7,9],size=10)
print(e)

[5 3 3 3 3 7 9 3 9 7]


In [ ]:
#np.concatenate((arr1,arr2).axis=None,0,1)
#np.hstack((arr1,arr2))
#np.vstack((arr1,arr2))
#np.copy()
#change dtype of int64 and flot64-->np.array(l,dtype=np.int32)
#np.zeros((row,col))
#np.ones((row,col))
#np.full(row,col,number)
#np.eye(N)
#np.linspace(start,end,no of partitions)
#unifrom data-->np.random.random((row,col))
#normal distribution--> np.random.randn(row,col)
#how can you say a data is randomly distributed--> mean is zero, varience is equal to 1 and std is equal to 1
#random_numbers_with specific size-->np.random.choice(range of numbers,size=number)
#generate range of random integers-->np.random.randint(start,end, size=(row,col))


# (30-05-2025)

**solving the linear systems**

In [ ]:
#x1 + x2 = 2200
#1.5x1 + 4x2 = 5050
import numpy as np
a = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.inv(a).dot(b)
print(x)

[1500.  700.]


In [ ]:
#instead we can use below formula
x = np.linalg.solve(a,b)
print(x)

[1500.  700.]


**Broadcasting Method**

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([[1,0,1]])
z = a + b
print(z)
'''broadcasting is a powerful mechanism that allows numpy to work with
different arrays of different shapes when performing the arthamatic operation'''


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
